-- Core RideMate schema: riders, groups, rides, live locations, chat and SOS.
-- Identity columns are bigint to match the tables already provisioned in
-- Supabase; every id therefore travels over the API as a numeric string.
create extension if not exists pgcrypto;

create table if not exists riders (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists groups (
  id bigint generated by default as identity primary key,
  name text not null,
  invite_code text unique not null
    default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6)),
  owner_id bigint references riders(id),
  created_at timestamptz not null default now()
);

create table if not exists group_members (
  group_id bigint not null references groups(id) on delete cascade,
  rider_id bigint not null references riders(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (group_id, rider_id)
);

create table if not exists rides (
  id bigint generated by default as identity primary key,
  group_id bigint not null references groups(id) on delete cascade,
  started_by bigint references riders(id),
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

-- One row per rider: their latest known position.
create table if not exists locations (
  rider_id bigint primary key references riders(id) on delete cascade,
  group_id bigint references groups(id) on delete cascade,
  ride_id bigint references rides(id) on delete set null,
  latitude double precision not null,
  longitude double precision not null,
  accuracy double precision,
  updated_at timestamptz not null default now()
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  group_id bigint not null references groups(id) on delete cascade,
  sender_id bigint references riders(id),
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists sos_alerts (
  id bigint generated by default as identity primary key,
  group_id bigint not null references groups(id) on delete cascade,
  rider_id bigint references riders(id),
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamptz not null default now()
);
