-- Fills the gaps in the provisioned schema: cancellable SOS alerts, rider
-- avatars, and the ride participation/location history that ride stats
-- (distance, duration, rider count) are derived from.

alter table riders add column if not exists avatar_url text;

-- Without these an SOS could be raised but never stood down.
alter table sos_alerts add column if not exists active boolean not null default true;
alter table sos_alerts add column if not exists cancelled_at timestamptz;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'messages_text_length') then
    alter table messages
      add constraint messages_text_length check (char_length(text) between 1 and 2000);
  end if;
end $$;

-- Who is taking part in a ride, and who has already ended it for themselves.
create table if not exists ride_participants (
  ride_id bigint not null references rides(id) on delete cascade,
  rider_id bigint not null references riders(id) on delete cascade,
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  primary key (ride_id, rider_id)
);

-- Append-only breadcrumb trail; `locations` only ever holds the latest fix.
create table if not exists ride_tracks (
  id bigint generated by default as identity primary key,
  ride_id bigint not null references rides(id) on delete cascade,
  rider_id bigint not null references riders(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  accuracy double precision,
  recorded_at timestamptz not null default now()
);

create index if not exists ride_tracks_ride_rider_idx
  on ride_tracks (ride_id, rider_id, recorded_at);
create index if not exists messages_group_created_idx
  on messages (group_id, created_at desc);
create index if not exists group_members_rider_idx on group_members (rider_id);
create index if not exists locations_group_idx on locations (group_id);
create index if not exists sos_alerts_group_active_idx on sos_alerts (group_id) where active;

-- A group can only have one ride running at a time.
create unique index if not exists rides_one_active_per_group
  on rides (group_id) where ended_at is null;

create or replace function haversine_km(
  lat1 double precision, lon1 double precision,
  lat2 double precision, lon2 double precision
) returns double precision language sql immutable as $$
  select 2 * 6371 * asin(sqrt(
    power(sin(radians(lat2 - lat1) / 2), 2)
    + cos(radians(lat1)) * cos(radians(lat2))
      * power(sin(radians(lon2 - lon1) / 2), 2)
  ));
$$;

-- Distance covered on a ride: the longest single-rider trail, since riders
-- join at different points and we want the length of the ride itself.
create or replace function ride_distance_km(target_ride bigint)
returns double precision language sql stable as $$
  with steps as (
    select
      rider_id,
      haversine_km(
        lag(latitude) over trail, lag(longitude) over trail, latitude, longitude
      ) as km
    from ride_tracks
    where ride_id = target_ride
    window trail as (partition by rider_id order by recorded_at)
  )
  select coalesce(max(total), 0)
  from (
    select rider_id, sum(km) as total from steps where km is not null group by rider_id
  ) per_rider;
$$;
